server:
  port: 48092
spring:
  application:
    name: LaneCallerService
  cloud:
    polaris:
      address: grpc://119.91.66.223:8091
      namespace: default
      enabled: true
      discovery:
        enabled: true
        register: true
        heartbeat:
          enabled: true
        health-check-url: /lane/caller/healthCheck
      contract:
        exposure: true
        report:
          enabled: true
      circuitbreaker:
        enabled: true
      stat:
        enabled: true
        port: 28082
    #        pushgateway:
    #          enabled: true
    #          address: 127.0.0.1:9091
    tencent:
      rpc-enhancement:
        enabled: true
        reporter:
          enabled: true
          ignore-internal-server-error: true
          series: server_error
          statuses: gateway_timeout, bad_gateway, service_unavailable
management:
  endpoints:
    web:
      exposure:
        include:
          - polaris-discovery