name: Codecov

on:
  push:
    branches:
      - hoxton
      - 2021.0
      - 2020.0
      - greenwich
  pull_request:
    branches:
      - hoxton
      - 2021.0
      - 2020.0
      - greenwich

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Test with Maven
        run: mvn clean test -f pom.xml -B -P sonatype -U
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
