name: Codecov

on:
  push:
    branches:
      - 2024
      - 2023
      - 2022
      - 2021
      - 2020
      - hoxton
      - greenwich
  pull_request:
    branches:
      - 2024
      - 2023
      - 2022
      - 2021
      - 2020
      - hoxton
      - greenwich

jobs:
  codecov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Test with Maven
        run: mvn clean test -B -U -Psonatype
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
