# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test with Junit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        java: [ 8, 11, 17 ]
        os: [ 'windows-latest', 'macos-latest', 'ubuntu-latest' ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout codes
      uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
#    - name: Build with Maven
#      run: mvn -B package --file pom.xml
    - name: Test with Maven
      run: mvn -B test --file pom.xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
