name: License checker

on:
  push:
    branches:
      - 2024
      - 2023
      - 2022
      - 2021
      - 2020
      - hoxton
      - greenwich
  pull_request:
    branches:
      - 2024
      - 2023
      - 2022
      - 2021
      - 2020
      - hoxton
      - greenwich
jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v4
      - name: Check License Header
        uses: apache/skywalking-eyes@v0.4.0
